version: '3.3'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5436:5432"
    expose:
      - 5432
    networks:
      - test-network
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=test_db

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - postgres
    networks:
      - test-network

networks:
  test-network:
    driver: bridge