// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	contract "github.com/JoaoLeal92/go_boilerplate/domain/contract"
	mock "github.com/stretchr/testify/mock"
)

// RepoManager is an autogenerated mock type for the RepoManager type
type RepoManager struct {
	mock.Mock
}

// Users provides a mock function with given fields:
func (_m *RepoManager) Users() contract.UserRepository {
	ret := _m.Called()

	var r0 contract.UserRepository
	if rf, ok := ret.Get(0).(func() contract.UserRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contract.UserRepository)
		}
	}

	return r0
}
